insert into EXCHANGE_VALUE(ID ,CURRENY_FROM ,CURRENY_TO ,CONVERSION_MULTIPLE ,PORT ) values(10001,'USD','INR',65,0);
insert into EXCHANGE_VALUE(ID ,CURRENY_FROM ,CURRENY_TO ,CONVERSION_MULTIPLE ,PORT ) values(10002,'EUR','INR',75,0);
insert into EXCHANGE_VALUE(ID ,CURRENY_FROM ,CURRENY_TO ,CONVERSION_MULTIPLE ,PORT ) values(10003,'AUD','INR',25,0);